-- Base seed: arsitektur-tradisional (1 slot × 38 provinsi)
-- category slug: arsitektur-tradisional
-- Lengkapi content/media, lalu jalankan SQL di Supabase.

BEGIN;

DELETE FROM cultures WHERE category_id = (SELECT id FROM categories WHERE slug = 'arsitektur-tradisional');

INSERT INTO cultures (province_id, category_id, name, content, media_url, location, maps_url, slug)
SELECT p.id, c.id, v.name, v.content, v.media_url, v.location, v.maps_url, v.slug
FROM (SELECT id FROM categories WHERE slug = 'arsitektur-tradisional') c
CROSS JOIN (VALUES
  ('aceh', 'Rumoh Aceh', '<p><strong>Rumoh Aceh</strong> adalah arsitektur tradisional khas Aceh.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Banda Aceh', 'https://www.google.com/maps/search/?api=1&query=Rumoh%20Aceh%20Aceh', 'rumoh-aceh'),
  ('sumatera-utara', 'Rumah Bolon', '<p><strong>Rumah Bolon</strong> adalah arsitektur tradisional khas Sumatera Utara.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Medan', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Bolon%20Sumatera%20Utara', 'rumah-bolon'),
  ('sumatera-barat', 'Rumah Gadang', '<p><strong>Rumah Gadang</strong> adalah arsitektur tradisional khas Sumatera Barat.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Padang', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Gadang%20Sumatera%20Barat', 'rumah-gadang'),
  ('riau', 'Rumah Melayu Riau', '<p><strong>Rumah Melayu Riau</strong> adalah arsitektur tradisional khas Riau.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Pekanbaru', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Melayu%20Riau%20Riau', 'rumah-melayu-riau'),
  ('jambi', 'Rumah Kajang Lako', '<p><strong>Rumah Kajang Lako</strong> adalah arsitektur tradisional khas Jambi.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Jambi', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Kajang%20Lako%20Jambi', 'rumah-kajang-lako'),
  ('sumatera-selatan', 'Rumah Limas', '<p><strong>Rumah Limas</strong> adalah arsitektur tradisional khas Sumatera Selatan.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Palembang', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Limas%20Sumatera%20Selatan', 'rumah-limas'),
  ('bengkulu', 'Rumah Bubungan Lima', '<p><strong>Rumah Bubungan Lima</strong> adalah arsitektur tradisional khas Bengkulu.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Bengkulu', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Bubungan%20Lima%20Bengkulu', 'rumah-bubungan-lima'),
  ('lampung', 'Nuwo Sesat', '<p><strong>Nuwo Sesat</strong> adalah arsitektur tradisional khas Lampung.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Bandar Lampung', 'https://www.google.com/maps/search/?api=1&query=Nuwo%20Sesat%20Lampung', 'nuwo-sesat'),
  ('kepulauan-bangka-belitung', 'Rumah Rakit Babel', '<p><strong>Rumah Rakit Babel</strong> adalah arsitektur tradisional khas Kepulauan Bangka Belitung.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Pangkalpinang', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Rakit%20Babel%20Kepulauan%20Bangka%20Belitung', 'rumah-rakit-babel'),
  ('kepulauan-riau', 'Rumah Melayu Kepri', '<p><strong>Rumah Melayu Kepri</strong> adalah arsitektur tradisional khas Kepulauan Riau.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Tanjung Pinang', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Melayu%20Kepri%20Kepulauan%20Riau', 'rumah-melayu-kepri'),
  ('dki-jakarta', 'Rumah Kebaya Betawi', '<p><strong>Rumah Kebaya Betawi</strong> adalah arsitektur tradisional khas DKI Jakarta.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Jakarta', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Kebaya%20Betawi%20DKI%20Jakarta', 'rumah-kebaya-betawi'),
  ('jawa-barat', 'Imah Sunda', '<p><strong>Imah Sunda</strong> adalah arsitektur tradisional khas Jawa Barat.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Bandung', 'https://www.google.com/maps/search/?api=1&query=Imah%20Sunda%20Jawa%20Barat', 'imah-sunda'),
  ('jawa-tengah', 'Joglo Jawa', '<p><strong>Joglo Jawa</strong> adalah arsitektur tradisional khas Jawa Tengah.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Surakarta', 'https://www.google.com/maps/search/?api=1&query=Joglo%20Jawa%20Jawa%20Tengah', 'joglo-jawa'),
  ('di-yogyakarta', 'Joglo Yogyakarta', '<p><strong>Joglo Yogyakarta</strong> adalah arsitektur tradisional khas DI Yogyakarta.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Yogyakarta', 'https://www.google.com/maps/search/?api=1&query=Joglo%20Yogyakarta%20DI%20Yogyakarta', 'joglo-yogyakarta'),
  ('jawa-timur', 'Joglo Jawa Timur', '<p><strong>Joglo Jawa Timur</strong> adalah arsitektur tradisional khas Jawa Timur.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Surabaya', 'https://www.google.com/maps/search/?api=1&query=Joglo%20Jawa%20Timur%20Jawa%20Timur', 'joglo-jawa-timur'),
  ('banten', 'Rumah Adat Banten', '<p><strong>Rumah Adat Banten</strong> adalah arsitektur tradisional khas Banten.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Serang', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Adat%20Banten%20Banten', 'rumah-adat-banten'),
  ('bali', 'Bale Bali', '<p><strong>Bale Bali</strong> adalah arsitektur tradisional khas Bali.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Denpasar', 'https://www.google.com/maps/search/?api=1&query=Bale%20Bali%20Bali', 'bale-bali'),
  ('nusa-tenggara-barat', 'Bale Tani Sasak', '<p><strong>Bale Tani Sasak</strong> adalah arsitektur tradisional khas Nusa Tenggara Barat.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Mataram', 'https://www.google.com/maps/search/?api=1&query=Bale%20Tani%20Sasak%20Nusa%20Tenggara%20Barat', 'bale-tani-sasak'),
  ('nusa-tenggara-timur', 'Sao Ria', '<p><strong>Sao Ria</strong> adalah arsitektur tradisional khas Nusa Tenggara Timur.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Kupang', 'https://www.google.com/maps/search/?api=1&query=Sao%20Ria%20Nusa%20Tenggara%20Timur', 'sao-ria'),
  ('kalimantan-barat', 'Rumah Panjang Dayak', '<p><strong>Rumah Panjang Dayak</strong> adalah arsitektur tradisional khas Kalimantan Barat.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Pontianak', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Panjang%20Dayak%20Kalimantan%20Barat', 'rumah-panjang-dayak'),
  ('kalimantan-tengah', 'Betang', '<p><strong>Betang</strong> adalah arsitektur tradisional khas Kalimantan Tengah.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Palangka Raya', 'https://www.google.com/maps/search/?api=1&query=Betang%20Kalimantan%20Tengah', 'betang'),
  ('kalimantan-selatan', 'Rumah Bubungan Tinggi', '<p><strong>Rumah Bubungan Tinggi</strong> adalah arsitektur tradisional khas Kalimantan Selatan.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Banjarmasin', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Bubungan%20Tinggi%20Kalimantan%20Selatan', 'rumah-bubungan-tinggi'),
  ('kalimantan-timur', 'Lamin', '<p><strong>Lamin</strong> adalah arsitektur tradisional khas Kalimantan Timur.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Samarinda', 'https://www.google.com/maps/search/?api=1&query=Lamin%20Kalimantan%20Timur', 'lamin'),
  ('kalimantan-utara', 'Baloy', '<p><strong>Baloy</strong> adalah arsitektur tradisional khas Kalimantan Utara.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Tanjung Selor', 'https://www.google.com/maps/search/?api=1&query=Baloy%20Kalimantan%20Utara', 'baloy'),
  ('sulawesi-utara', 'Wale', '<p><strong>Wale</strong> adalah arsitektur tradisional khas Sulawesi Utara.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Manado', 'https://www.google.com/maps/search/?api=1&query=Wale%20Sulawesi%20Utara', 'wale'),
  ('sulawesi-tengah', 'Souraja', '<p><strong>Souraja</strong> adalah arsitektur tradisional khas Sulawesi Tengah.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Palu', 'https://www.google.com/maps/search/?api=1&query=Souraja%20Sulawesi%20Tengah', 'souraja'),
  ('sulawesi-selatan', 'Tongkonan', '<p><strong>Tongkonan</strong> adalah arsitektur tradisional khas Sulawesi Selatan.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Makassar', 'https://www.google.com/maps/search/?api=1&query=Tongkonan%20Sulawesi%20Selatan', 'tongkonan'),
  ('sulawesi-tenggara', 'Laika', '<p><strong>Laika</strong> adalah arsitektur tradisional khas Sulawesi Tenggara.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Kendari', 'https://www.google.com/maps/search/?api=1&query=Laika%20Sulawesi%20Tenggara', 'laika'),
  ('gorontalo', 'Dulohupa', '<p><strong>Dulohupa</strong> adalah arsitektur tradisional khas Gorontalo.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Gorontalo', 'https://www.google.com/maps/search/?api=1&query=Dulohupa%20Gorontalo', 'dulohupa'),
  ('sulawesi-barat', 'Boyang', '<p><strong>Boyang</strong> adalah arsitektur tradisional khas Sulawesi Barat.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Mamuju', 'https://www.google.com/maps/search/?api=1&query=Boyang%20Sulawesi%20Barat', 'boyang'),
  ('maluku', 'Baileo', '<p><strong>Baileo</strong> adalah arsitektur tradisional khas Maluku.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Ambon', 'https://www.google.com/maps/search/?api=1&query=Baileo%20Maluku', 'baileo'),
  ('maluku-utara', 'Sasadu', '<p><strong>Sasadu</strong> adalah arsitektur tradisional khas Maluku Utara.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Ternate', 'https://www.google.com/maps/search/?api=1&query=Sasadu%20Maluku%20Utara', 'sasadu'),
  ('papua', 'Honai', '<p><strong>Honai</strong> adalah arsitektur tradisional khas Papua.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Jayapura', 'https://www.google.com/maps/search/?api=1&query=Honai%20Papua', 'honai'),
  ('papua-barat', 'Rumah Kaki Seribu', '<p><strong>Rumah Kaki Seribu</strong> adalah arsitektur tradisional khas Papua Barat.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Manokwari', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Kaki%20Seribu%20Papua%20Barat', 'rumah-kaki-seribu'),
  ('papua-selatan', 'Rumah Adat Papua Selatan', '<p><strong>Rumah Adat Papua Selatan</strong> adalah arsitektur tradisional khas Papua Selatan.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Merauke', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Adat%20Papua%20Selatan%20Papua%20Selatan', 'rumah-adat-papua-selatan'),
  ('papua-tengah', 'Rumah Adat Papua Tengah', '<p><strong>Rumah Adat Papua Tengah</strong> adalah arsitektur tradisional khas Papua Tengah.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Nabire', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Adat%20Papua%20Tengah%20Papua%20Tengah', 'rumah-adat-papua-tengah'),
  ('papua-pegunungan', 'Honai Pegunungan', '<p><strong>Honai Pegunungan</strong> adalah arsitektur tradisional khas Papua Pegunungan.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Wamena', 'https://www.google.com/maps/search/?api=1&query=Honai%20Pegunungan%20Papua%20Pegunungan', 'honai-pegunungan'),
  ('papua-barat-daya', 'Rumah Adat Papua Barat Daya', '<p><strong>Rumah Adat Papua Barat Daya</strong> adalah arsitektur tradisional khas Papua Barat Daya.</p><p>TODO: lengkapi sejarah, struktur bangunan, bahan, dan makna filosofis.</p>', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80', 'Sorong', 'https://www.google.com/maps/search/?api=1&query=Rumah%20Adat%20Papua%20Barat%20Daya%20Papua%20Barat%20Daya', 'rumah-adat-papua-barat-daya')
) AS v(province_slug, name, content, media_url, location, maps_url, slug)
JOIN provinces p ON p.slug = v.province_slug;

COMMIT;
