-- Base seed: bahasa-dan-sastra (1 slot × 38 provinsi)
-- category slug: bahasa-dan-sastra
-- Lengkapi content/media, lalu jalankan SQL di Supabase.

BEGIN;

DELETE FROM cultures WHERE category_id = (SELECT id FROM categories WHERE slug = 'bahasa-dan-sastra');

INSERT INTO cultures (province_id, category_id, name, content, media_url, location, maps_url, slug)
SELECT p.id, c.id, v.name, v.content, v.media_url, v.location, v.maps_url, v.slug
FROM (SELECT id FROM categories WHERE slug = 'bahasa-dan-sastra') c
CROSS JOIN (VALUES
  ('aceh', 'Hikayat Aceh', '<p><strong>Hikayat Aceh</strong> adalah bahasa dan sastra khas Aceh.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Banda Aceh', 'https://www.google.com/maps/search/?api=1&query=Hikayat%20Aceh%20Aceh', 'hikayat-aceh'),
  ('sumatera-utara', 'Umrapa Batak', '<p><strong>Umrapa Batak</strong> adalah bahasa dan sastra khas Sumatera Utara.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Medan', 'https://www.google.com/maps/search/?api=1&query=Umrapa%20Batak%20Sumatera%20Utara', 'umrapa-batak'),
  ('sumatera-barat', 'Kaba Minangkabau', '<p><strong>Kaba Minangkabau</strong> adalah bahasa dan sastra khas Sumatera Barat.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Padang', 'https://www.google.com/maps/search/?api=1&query=Kaba%20Minangkabau%20Sumatera%20Barat', 'kaba-minangkabau'),
  ('riau', 'Gurindam Dua Belas', '<p><strong>Gurindam Dua Belas</strong> adalah bahasa dan sastra khas Riau.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Pekanbaru', 'https://www.google.com/maps/search/?api=1&query=Gurindam%20Dua%20Belas%20Riau', 'gurindam-dua-belas'),
  ('jambi', 'Seloko Adat Jambi', '<p><strong>Seloko Adat Jambi</strong> adalah bahasa dan sastra khas Jambi.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Jambi', 'https://www.google.com/maps/search/?api=1&query=Seloko%20Adat%20Jambi%20Jambi', 'seloko-adat-jambi'),
  ('sumatera-selatan', 'Andai-andai Palembang', '<p><strong>Andai-andai Palembang</strong> adalah bahasa dan sastra khas Sumatera Selatan.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Palembang', 'https://www.google.com/maps/search/?api=1&query=Andai-andai%20Palembang%20Sumatera%20Selatan', 'andai-andai-palembang'),
  ('bengkulu', 'Rejung Bengkulu', '<p><strong>Rejung Bengkulu</strong> adalah bahasa dan sastra khas Bengkulu.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Bengkulu', 'https://www.google.com/maps/search/?api=1&query=Rejung%20Bengkulu%20Bengkulu', 'rejung-bengkulu'),
  ('lampung', 'Pisaan Lampung', '<p><strong>Pisaan Lampung</strong> adalah bahasa dan sastra khas Lampung.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Bandar Lampung', 'https://www.google.com/maps/search/?api=1&query=Pisaan%20Lampung%20Lampung', 'pisaan-lampung'),
  ('kepulauan-bangka-belitung', 'Pantun Babel', '<p><strong>Pantun Babel</strong> adalah bahasa dan sastra khas Kepulauan Bangka Belitung.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Pangkalpinang', 'https://www.google.com/maps/search/?api=1&query=Pantun%20Babel%20Kepulauan%20Bangka%20Belitung', 'pantun-babel'),
  ('kepulauan-riau', 'Gurindam Kepri', '<p><strong>Gurindam Kepri</strong> adalah bahasa dan sastra khas Kepulauan Riau.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Tanjung Pinang', 'https://www.google.com/maps/search/?api=1&query=Gurindam%20Kepri%20Kepulauan%20Riau', 'gurindam-kepri'),
  ('dki-jakarta', 'Pantun Betawi', '<p><strong>Pantun Betawi</strong> adalah bahasa dan sastra khas DKI Jakarta.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Jakarta', 'https://www.google.com/maps/search/?api=1&query=Pantun%20Betawi%20DKI%20Jakarta', 'pantun-betawi'),
  ('jawa-barat', 'Carita Pantun Sunda', '<p><strong>Carita Pantun Sunda</strong> adalah bahasa dan sastra khas Jawa Barat.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Bandung', 'https://www.google.com/maps/search/?api=1&query=Carita%20Pantun%20Sunda%20Jawa%20Barat', 'carita-pantun-sunda'),
  ('jawa-tengah', 'Serat Jawa', '<p><strong>Serat Jawa</strong> adalah bahasa dan sastra khas Jawa Tengah.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Surakarta', 'https://www.google.com/maps/search/?api=1&query=Serat%20Jawa%20Jawa%20Tengah', 'serat-jawa'),
  ('di-yogyakarta', 'Serat Yogyakarta', '<p><strong>Serat Yogyakarta</strong> adalah bahasa dan sastra khas DI Yogyakarta.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Yogyakarta', 'https://www.google.com/maps/search/?api=1&query=Serat%20Yogyakarta%20DI%20Yogyakarta', 'serat-yogyakarta'),
  ('jawa-timur', 'Paparin Madura', '<p><strong>Paparin Madura</strong> adalah bahasa dan sastra khas Jawa Timur.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Surabaya', 'https://www.google.com/maps/search/?api=1&query=Paparin%20Madura%20Jawa%20Timur', 'paparin-madura'),
  ('banten', 'Pantun Banten', '<p><strong>Pantun Banten</strong> adalah bahasa dan sastra khas Banten.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Serang', 'https://www.google.com/maps/search/?api=1&query=Pantun%20Banten%20Banten', 'pantun-banten'),
  ('bali', 'Kakawin Bali', '<p><strong>Kakawin Bali</strong> adalah bahasa dan sastra khas Bali.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Denpasar', 'https://www.google.com/maps/search/?api=1&query=Kakawin%20Bali%20Bali', 'kakawin-bali'),
  ('nusa-tenggara-barat', 'Awiq-awiq Sasak', '<p><strong>Awiq-awiq Sasak</strong> adalah bahasa dan sastra khas Nusa Tenggara Barat.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Mataram', 'https://www.google.com/maps/search/?api=1&query=Awiq-awiq%20Sasak%20Nusa%20Tenggara%20Barat', 'awiq-awiq-sasak'),
  ('nusa-tenggara-timur', 'Tuturan Adat NTT', '<p><strong>Tuturan Adat NTT</strong> adalah bahasa dan sastra khas Nusa Tenggara Timur.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Kupang', 'https://www.google.com/maps/search/?api=1&query=Tuturan%20Adat%20NTT%20Nusa%20Tenggara%20Timur', 'tuturan-adat-ntt'),
  ('kalimantan-barat', 'Pantun Dayak', '<p><strong>Pantun Dayak</strong> adalah bahasa dan sastra khas Kalimantan Barat.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Pontianak', 'https://www.google.com/maps/search/?api=1&query=Pantun%20Dayak%20Kalimantan%20Barat', 'pantun-dayak'),
  ('kalimantan-tengah', 'Karungut', '<p><strong>Karungut</strong> adalah bahasa dan sastra khas Kalimantan Tengah.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Palangka Raya', 'https://www.google.com/maps/search/?api=1&query=Karungut%20Kalimantan%20Tengah', 'karungut'),
  ('kalimantan-selatan', 'Madihin', '<p><strong>Madihin</strong> adalah bahasa dan sastra khas Kalimantan Selatan.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Banjarmasin', 'https://www.google.com/maps/search/?api=1&query=Madihin%20Kalimantan%20Selatan', 'madihin'),
  ('kalimantan-timur', 'Tuturan Kutai', '<p><strong>Tuturan Kutai</strong> adalah bahasa dan sastra khas Kalimantan Timur.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Samarinda', 'https://www.google.com/maps/search/?api=1&query=Tuturan%20Kutai%20Kalimantan%20Timur', 'tuturan-kutai'),
  ('kalimantan-utara', 'Pantun Kaltara', '<p><strong>Pantun Kaltara</strong> adalah bahasa dan sastra khas Kalimantan Utara.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Tanjung Selor', 'https://www.google.com/maps/search/?api=1&query=Pantun%20Kaltara%20Kalimantan%20Utara', 'pantun-kaltara'),
  ('sulawesi-utara', 'Sastra Minahasa', '<p><strong>Sastra Minahasa</strong> adalah bahasa dan sastra khas Sulawesi Utara.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Manado', 'https://www.google.com/maps/search/?api=1&query=Sastra%20Minahasa%20Sulawesi%20Utara', 'sastra-minahasa'),
  ('sulawesi-tengah', 'Tuturan Kaili', '<p><strong>Tuturan Kaili</strong> adalah bahasa dan sastra khas Sulawesi Tengah.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Palu', 'https://www.google.com/maps/search/?api=1&query=Tuturan%20Kaili%20Sulawesi%20Tengah', 'tuturan-kaili'),
  ('sulawesi-selatan', 'Sureq Galigo', '<p><strong>Sureq Galigo</strong> adalah bahasa dan sastra khas Sulawesi Selatan.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Makassar', 'https://www.google.com/maps/search/?api=1&query=Sureq%20Galigo%20Sulawesi%20Selatan', 'sureq-galigo'),
  ('sulawesi-tenggara', 'Tuturan Tolaki', '<p><strong>Tuturan Tolaki</strong> adalah bahasa dan sastra khas Sulawesi Tenggara.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Kendari', 'https://www.google.com/maps/search/?api=1&query=Tuturan%20Tolaki%20Sulawesi%20Tenggara', 'tuturan-tolaki'),
  ('gorontalo', 'Tujaqi', '<p><strong>Tujaqi</strong> adalah bahasa dan sastra khas Gorontalo.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Gorontalo', 'https://www.google.com/maps/search/?api=1&query=Tujaqi%20Gorontalo', 'tujaqi'),
  ('sulawesi-barat', 'Kalindaqdaq Mandar', '<p><strong>Kalindaqdaq Mandar</strong> adalah bahasa dan sastra khas Sulawesi Barat.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Mamuju', 'https://www.google.com/maps/search/?api=1&query=Kalindaqdaq%20Mandar%20Sulawesi%20Barat', 'kalindaqdaq-mandar'),
  ('maluku', 'Kapata', '<p><strong>Kapata</strong> adalah bahasa dan sastra khas Maluku.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Ambon', 'https://www.google.com/maps/search/?api=1&query=Kapata%20Maluku', 'kapata'),
  ('maluku-utara', 'Dalil Ternate', '<p><strong>Dalil Ternate</strong> adalah bahasa dan sastra khas Maluku Utara.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Ternate', 'https://www.google.com/maps/search/?api=1&query=Dalil%20Ternate%20Maluku%20Utara', 'dalil-ternate'),
  ('papua', 'Tuturan Adat Papua', '<p><strong>Tuturan Adat Papua</strong> adalah bahasa dan sastra khas Papua.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Jayapura', 'https://www.google.com/maps/search/?api=1&query=Tuturan%20Adat%20Papua%20Papua', 'tuturan-adat-papua'),
  ('papua-barat', 'Tuturan Adat Papua Barat', '<p><strong>Tuturan Adat Papua Barat</strong> adalah bahasa dan sastra khas Papua Barat.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Manokwari', 'https://www.google.com/maps/search/?api=1&query=Tuturan%20Adat%20Papua%20Barat%20Papua%20Barat', 'tuturan-adat-papua-barat'),
  ('papua-selatan', 'Tuturan Adat Papua Selatan', '<p><strong>Tuturan Adat Papua Selatan</strong> adalah bahasa dan sastra khas Papua Selatan.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Merauke', 'https://www.google.com/maps/search/?api=1&query=Tuturan%20Adat%20Papua%20Selatan%20Papua%20Selatan', 'tuturan-adat-papua-selatan'),
  ('papua-tengah', 'Tuturan Adat Papua Tengah', '<p><strong>Tuturan Adat Papua Tengah</strong> adalah bahasa dan sastra khas Papua Tengah.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Nabire', 'https://www.google.com/maps/search/?api=1&query=Tuturan%20Adat%20Papua%20Tengah%20Papua%20Tengah', 'tuturan-adat-papua-tengah'),
  ('papua-pegunungan', 'Tuturan Adat Pegunungan', '<p><strong>Tuturan Adat Pegunungan</strong> adalah bahasa dan sastra khas Papua Pegunungan.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Wamena', 'https://www.google.com/maps/search/?api=1&query=Tuturan%20Adat%20Pegunungan%20Papua%20Pegunungan', 'tuturan-adat-pegunungan'),
  ('papua-barat-daya', 'Tuturan Adat Papua Barat Daya', '<p><strong>Tuturan Adat Papua Barat Daya</strong> adalah bahasa dan sastra khas Papua Barat Daya.</p><p>TODO: lengkapi sejarah, ciri bahasa/sastra, dan konteks pemakaian.</p>', 'https://images.unsplash.com/photo-1456513080880-7d36c0a0f0c1?w=1200&q=80', 'Sorong', 'https://www.google.com/maps/search/?api=1&query=Tuturan%20Adat%20Papua%20Barat%20Daya%20Papua%20Barat%20Daya', 'tuturan-adat-papua-barat-daya')
) AS v(province_slug, name, content, media_url, location, maps_url, slug)
JOIN provinces p ON p.slug = v.province_slug;

COMMIT;
