-- Base seed: kerajinan (1 slot × 38 provinsi)
-- category slug: kerajinan
-- Lengkapi content/media, lalu jalankan SQL di Supabase.

BEGIN;

DELETE FROM cultures WHERE category_id = (SELECT id FROM categories WHERE slug = 'kerajinan');

INSERT INTO cultures (province_id, category_id, name, content, media_url, location, maps_url, slug)
SELECT p.id, c.id, v.name, v.content, v.media_url, v.location, v.maps_url, v.slug
FROM (SELECT id FROM categories WHERE slug = 'kerajinan') c
CROSS JOIN (VALUES
  ('aceh', 'Kerajinan Rencong Aceh', '<p><strong>Kerajinan Rencong Aceh</strong> adalah kerajinan khas Aceh.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Banda Aceh', 'https://www.google.com/maps/search/?api=1&query=Kerajinan%20Rencong%20Aceh%20Aceh', 'kerajinan-rencong-aceh'),
  ('sumatera-utara', 'Ulos Tenun Batak', '<p><strong>Ulos Tenun Batak</strong> adalah kerajinan khas Sumatera Utara.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Medan', 'https://www.google.com/maps/search/?api=1&query=Ulos%20Tenun%20Batak%20Sumatera%20Utara', 'ulos-tenun-batak'),
  ('sumatera-barat', 'Songket Minangkabau', '<p><strong>Songket Minangkabau</strong> adalah kerajinan khas Sumatera Barat.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Padang', 'https://www.google.com/maps/search/?api=1&query=Songket%20Minangkabau%20Sumatera%20Barat', 'songket-minangkabau'),
  ('riau', 'Songket Melayu Riau', '<p><strong>Songket Melayu Riau</strong> adalah kerajinan khas Riau.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Pekanbaru', 'https://www.google.com/maps/search/?api=1&query=Songket%20Melayu%20Riau%20Riau', 'songket-melayu-riau'),
  ('jambi', 'Batik Jambi', '<p><strong>Batik Jambi</strong> adalah kerajinan khas Jambi.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Jambi', 'https://www.google.com/maps/search/?api=1&query=Batik%20Jambi%20Jambi', 'batik-jambi'),
  ('sumatera-selatan', 'Songket Palembang', '<p><strong>Songket Palembang</strong> adalah kerajinan khas Sumatera Selatan.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Palembang', 'https://www.google.com/maps/search/?api=1&query=Songket%20Palembang%20Sumatera%20Selatan', 'songket-palembang'),
  ('bengkulu', 'Batik Besurek', '<p><strong>Batik Besurek</strong> adalah kerajinan khas Bengkulu.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Bengkulu', 'https://www.google.com/maps/search/?api=1&query=Batik%20Besurek%20Bengkulu', 'batik-besurek'),
  ('lampung', 'Tenun Tapis', '<p><strong>Tenun Tapis</strong> adalah kerajinan khas Lampung.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Bandar Lampung', 'https://www.google.com/maps/search/?api=1&query=Tenun%20Tapis%20Lampung', 'tenun-tapis'),
  ('kepulauan-bangka-belitung', 'Kerajinan Timah Babel', '<p><strong>Kerajinan Timah Babel</strong> adalah kerajinan khas Kepulauan Bangka Belitung.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Pangkalpinang', 'https://www.google.com/maps/search/?api=1&query=Kerajinan%20Timah%20Babel%20Kepulauan%20Bangka%20Belitung', 'kerajinan-timah-babel'),
  ('kepulauan-riau', 'Songket Melayu Kepri', '<p><strong>Songket Melayu Kepri</strong> adalah kerajinan khas Kepulauan Riau.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Tanjung Pinang', 'https://www.google.com/maps/search/?api=1&query=Songket%20Melayu%20Kepri%20Kepulauan%20Riau', 'songket-melayu-kepri'),
  ('dki-jakarta', 'Kerajinan Ondel-ondel', '<p><strong>Kerajinan Ondel-ondel</strong> adalah kerajinan khas DKI Jakarta.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Jakarta', 'https://www.google.com/maps/search/?api=1&query=Kerajinan%20Ondel-ondel%20DKI%20Jakarta', 'kerajinan-ondel-ondel'),
  ('jawa-barat', 'Batik Megamendung', '<p><strong>Batik Megamendung</strong> adalah kerajinan khas Jawa Barat.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Bandung', 'https://www.google.com/maps/search/?api=1&query=Batik%20Megamendung%20Jawa%20Barat', 'batik-megamendung'),
  ('jawa-tengah', 'Batik Solo', '<p><strong>Batik Solo</strong> adalah kerajinan khas Jawa Tengah.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Surakarta', 'https://www.google.com/maps/search/?api=1&query=Batik%20Solo%20Jawa%20Tengah', 'batik-solo'),
  ('di-yogyakarta', 'Batik Yogyakarta', '<p><strong>Batik Yogyakarta</strong> adalah kerajinan khas DI Yogyakarta.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Yogyakarta', 'https://www.google.com/maps/search/?api=1&query=Batik%20Yogyakarta%20DI%20Yogyakarta', 'batik-yogyakarta'),
  ('jawa-timur', 'Batik Madura', '<p><strong>Batik Madura</strong> adalah kerajinan khas Jawa Timur.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Surabaya', 'https://www.google.com/maps/search/?api=1&query=Batik%20Madura%20Jawa%20Timur', 'batik-madura'),
  ('banten', 'Gerabah Banten', '<p><strong>Gerabah Banten</strong> adalah kerajinan khas Banten.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Serang', 'https://www.google.com/maps/search/?api=1&query=Gerabah%20Banten%20Banten', 'gerabah-banten'),
  ('bali', 'Ukiran Kayu Bali', '<p><strong>Ukiran Kayu Bali</strong> adalah kerajinan khas Bali.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Denpasar', 'https://www.google.com/maps/search/?api=1&query=Ukiran%20Kayu%20Bali%20Bali', 'ukiran-kayu-bali'),
  ('nusa-tenggara-barat', 'Tenun Songket Lombok', '<p><strong>Tenun Songket Lombok</strong> adalah kerajinan khas Nusa Tenggara Barat.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Mataram', 'https://www.google.com/maps/search/?api=1&query=Tenun%20Songket%20Lombok%20Nusa%20Tenggara%20Barat', 'tenun-songket-lombok'),
  ('nusa-tenggara-timur', 'Tenun Ikat NTT', '<p><strong>Tenun Ikat NTT</strong> adalah kerajinan khas Nusa Tenggara Timur.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Kupang', 'https://www.google.com/maps/search/?api=1&query=Tenun%20Ikat%20NTT%20Nusa%20Tenggara%20Timur', 'tenun-ikat-ntt'),
  ('kalimantan-barat', 'Anyaman Rotan Dayak', '<p><strong>Anyaman Rotan Dayak</strong> adalah kerajinan khas Kalimantan Barat.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Pontianak', 'https://www.google.com/maps/search/?api=1&query=Anyaman%20Rotan%20Dayak%20Kalimantan%20Barat', 'anyaman-rotan-dayak'),
  ('kalimantan-tengah', 'Anyaman Purun Kalteng', '<p><strong>Anyaman Purun Kalteng</strong> adalah kerajinan khas Kalimantan Tengah.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Palangka Raya', 'https://www.google.com/maps/search/?api=1&query=Anyaman%20Purun%20Kalteng%20Kalimantan%20Tengah', 'anyaman-purun-kalteng'),
  ('kalimantan-selatan', 'Sasirangan', '<p><strong>Sasirangan</strong> adalah kerajinan khas Kalimantan Selatan.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Banjarmasin', 'https://www.google.com/maps/search/?api=1&query=Sasirangan%20Kalimantan%20Selatan', 'sasirangan'),
  ('kalimantan-timur', 'Tenun Ulap Doyo', '<p><strong>Tenun Ulap Doyo</strong> adalah kerajinan khas Kalimantan Timur.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Samarinda', 'https://www.google.com/maps/search/?api=1&query=Tenun%20Ulap%20Doyo%20Kalimantan%20Timur', 'tenun-ulap-doyo'),
  ('kalimantan-utara', 'Anyaman Dayak Kaltara', '<p><strong>Anyaman Dayak Kaltara</strong> adalah kerajinan khas Kalimantan Utara.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Tanjung Selor', 'https://www.google.com/maps/search/?api=1&query=Anyaman%20Dayak%20Kaltara%20Kalimantan%20Utara', 'anyaman-dayak-kaltara'),
  ('sulawesi-utara', 'Kerajinan Kayu Minahasa', '<p><strong>Kerajinan Kayu Minahasa</strong> adalah kerajinan khas Sulawesi Utara.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Manado', 'https://www.google.com/maps/search/?api=1&query=Kerajinan%20Kayu%20Minahasa%20Sulawesi%20Utara', 'kerajinan-kayu-minahasa'),
  ('sulawesi-tengah', 'Kain Donggala', '<p><strong>Kain Donggala</strong> adalah kerajinan khas Sulawesi Tengah.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Palu', 'https://www.google.com/maps/search/?api=1&query=Kain%20Donggala%20Sulawesi%20Tengah', 'kain-donggala'),
  ('sulawesi-selatan', 'Tenun Sutera Bugis', '<p><strong>Tenun Sutera Bugis</strong> adalah kerajinan khas Sulawesi Selatan.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Makassar', 'https://www.google.com/maps/search/?api=1&query=Tenun%20Sutera%20Bugis%20Sulawesi%20Selatan', 'tenun-sutera-bugis'),
  ('sulawesi-tenggara', 'Tenun Tolaki', '<p><strong>Tenun Tolaki</strong> adalah kerajinan khas Sulawesi Tenggara.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Kendari', 'https://www.google.com/maps/search/?api=1&query=Tenun%20Tolaki%20Sulawesi%20Tenggara', 'tenun-tolaki'),
  ('gorontalo', 'Kerajinan Karawo', '<p><strong>Kerajinan Karawo</strong> adalah kerajinan khas Gorontalo.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Gorontalo', 'https://www.google.com/maps/search/?api=1&query=Kerajinan%20Karawo%20Gorontalo', 'kerajinan-karawo'),
  ('sulawesi-barat', 'Tenun Mandar', '<p><strong>Tenun Mandar</strong> adalah kerajinan khas Sulawesi Barat.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Mamuju', 'https://www.google.com/maps/search/?api=1&query=Tenun%20Mandar%20Sulawesi%20Barat', 'tenun-mandar'),
  ('maluku', 'Kerajinan Mutiara Maluku', '<p><strong>Kerajinan Mutiara Maluku</strong> adalah kerajinan khas Maluku.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Ambon', 'https://www.google.com/maps/search/?api=1&query=Kerajinan%20Mutiara%20Maluku%20Maluku', 'kerajinan-mutiara-maluku'),
  ('maluku-utara', 'Kerajinan Ternate', '<p><strong>Kerajinan Ternate</strong> adalah kerajinan khas Maluku Utara.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Ternate', 'https://www.google.com/maps/search/?api=1&query=Kerajinan%20Ternate%20Maluku%20Utara', 'kerajinan-ternate'),
  ('papua', 'Ukiran Asmat', '<p><strong>Ukiran Asmat</strong> adalah kerajinan khas Papua.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Jayapura', 'https://www.google.com/maps/search/?api=1&query=Ukiran%20Asmat%20Papua', 'ukiran-asmat'),
  ('papua-barat', 'Noken Papua Barat', '<p><strong>Noken Papua Barat</strong> adalah kerajinan khas Papua Barat.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Manokwari', 'https://www.google.com/maps/search/?api=1&query=Noken%20Papua%20Barat%20Papua%20Barat', 'noken-papua-barat'),
  ('papua-selatan', 'Noken Papua Selatan', '<p><strong>Noken Papua Selatan</strong> adalah kerajinan khas Papua Selatan.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Merauke', 'https://www.google.com/maps/search/?api=1&query=Noken%20Papua%20Selatan%20Papua%20Selatan', 'noken-papua-selatan'),
  ('papua-tengah', 'Ukiran Papua Tengah', '<p><strong>Ukiran Papua Tengah</strong> adalah kerajinan khas Papua Tengah.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Nabire', 'https://www.google.com/maps/search/?api=1&query=Ukiran%20Papua%20Tengah%20Papua%20Tengah', 'ukiran-papua-tengah'),
  ('papua-pegunungan', 'Noken Papua Pegunungan', '<p><strong>Noken Papua Pegunungan</strong> adalah kerajinan khas Papua Pegunungan.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Wamena', 'https://www.google.com/maps/search/?api=1&query=Noken%20Papua%20Pegunungan%20Papua%20Pegunungan', 'noken-papua-pegunungan'),
  ('papua-barat-daya', 'Kerajinan Raja Ampat', '<p><strong>Kerajinan Raja Ampat</strong> adalah kerajinan khas Papua Barat Daya.</p><p>TODO: lengkapi sejarah, bahan, teknik pembuatan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1200&q=80', 'Sorong', 'https://www.google.com/maps/search/?api=1&query=Kerajinan%20Raja%20Ampat%20Papua%20Barat%20Daya', 'kerajinan-raja-ampat')
) AS v(province_slug, name, content, media_url, location, maps_url, slug)
JOIN provinces p ON p.slug = v.province_slug;

COMMIT;
