-- Base seed: musik-tradisional (1 slot × 38 provinsi)
-- category slug: musik-tradisional
-- Lengkapi content/media, lalu jalankan SQL di Supabase.

BEGIN;

DELETE FROM cultures WHERE category_id = (SELECT id FROM categories WHERE slug = 'musik-tradisional');

INSERT INTO cultures (province_id, category_id, name, content, media_url, location, maps_url, slug)
SELECT p.id, c.id, v.name, v.content, v.media_url, v.location, v.maps_url, v.slug
FROM (SELECT id FROM categories WHERE slug = 'musik-tradisional') c
CROSS JOIN (VALUES
  ('aceh', 'Rapai Aceh', '<p><strong>Rapai Aceh</strong> adalah musik tradisional khas Aceh.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Banda Aceh', 'https://www.google.com/maps/search/?api=1&query=Rapai%20Aceh%20Aceh', 'rapai-aceh'),
  ('sumatera-utara', 'Gondang Batak', '<p><strong>Gondang Batak</strong> adalah musik tradisional khas Sumatera Utara.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Medan', 'https://www.google.com/maps/search/?api=1&query=Gondang%20Batak%20Sumatera%20Utara', 'gondang-batak'),
  ('sumatera-barat', 'Talempong', '<p><strong>Talempong</strong> adalah musik tradisional khas Sumatera Barat.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Padang', 'https://www.google.com/maps/search/?api=1&query=Talempong%20Sumatera%20Barat', 'talempong'),
  ('riau', 'Gambus Melayu Riau', '<p><strong>Gambus Melayu Riau</strong> adalah musik tradisional khas Riau.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Pekanbaru', 'https://www.google.com/maps/search/?api=1&query=Gambus%20Melayu%20Riau%20Riau', 'gambus-melayu-riau'),
  ('jambi', 'Krinok', '<p><strong>Krinok</strong> adalah musik tradisional khas Jambi.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Jambi', 'https://www.google.com/maps/search/?api=1&query=Krinok%20Jambi', 'krinok'),
  ('sumatera-selatan', 'Gamelan Palembang', '<p><strong>Gamelan Palembang</strong> adalah musik tradisional khas Sumatera Selatan.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Palembang', 'https://www.google.com/maps/search/?api=1&query=Gamelan%20Palembang%20Sumatera%20Selatan', 'gamelan-palembang'),
  ('bengkulu', 'Serunai Bengkulu', '<p><strong>Serunai Bengkulu</strong> adalah musik tradisional khas Bengkulu.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Bengkulu', 'https://www.google.com/maps/search/?api=1&query=Serunai%20Bengkulu%20Bengkulu', 'serunai-bengkulu'),
  ('lampung', 'Talo Balak', '<p><strong>Talo Balak</strong> adalah musik tradisional khas Lampung.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Bandar Lampung', 'https://www.google.com/maps/search/?api=1&query=Talo%20Balak%20Lampung', 'talo-balak'),
  ('kepulauan-bangka-belitung', 'Dambus', '<p><strong>Dambus</strong> adalah musik tradisional khas Kepulauan Bangka Belitung.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Pangkalpinang', 'https://www.google.com/maps/search/?api=1&query=Dambus%20Kepulauan%20Bangka%20Belitung', 'dambus'),
  ('kepulauan-riau', 'Gambus Kepri', '<p><strong>Gambus Kepri</strong> adalah musik tradisional khas Kepulauan Riau.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Tanjung Pinang', 'https://www.google.com/maps/search/?api=1&query=Gambus%20Kepri%20Kepulauan%20Riau', 'gambus-kepri'),
  ('dki-jakarta', 'Gambang Kromong', '<p><strong>Gambang Kromong</strong> adalah musik tradisional khas DKI Jakarta.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Jakarta', 'https://www.google.com/maps/search/?api=1&query=Gambang%20Kromong%20DKI%20Jakarta', 'gambang-kromong'),
  ('jawa-barat', 'Angklung', '<p><strong>Angklung</strong> adalah musik tradisional khas Jawa Barat.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Bandung', 'https://www.google.com/maps/search/?api=1&query=Angklung%20Jawa%20Barat', 'angklung'),
  ('jawa-tengah', 'Gamelan Jawa', '<p><strong>Gamelan Jawa</strong> adalah musik tradisional khas Jawa Tengah.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Surakarta', 'https://www.google.com/maps/search/?api=1&query=Gamelan%20Jawa%20Jawa%20Tengah', 'gamelan-jawa'),
  ('di-yogyakarta', 'Gamelan Yogyakarta', '<p><strong>Gamelan Yogyakarta</strong> adalah musik tradisional khas DI Yogyakarta.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Yogyakarta', 'https://www.google.com/maps/search/?api=1&query=Gamelan%20Yogyakarta%20DI%20Yogyakarta', 'gamelan-yogyakarta'),
  ('jawa-timur', 'Gamelan Jawa Timur', '<p><strong>Gamelan Jawa Timur</strong> adalah musik tradisional khas Jawa Timur.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Surabaya', 'https://www.google.com/maps/search/?api=1&query=Gamelan%20Jawa%20Timur%20Jawa%20Timur', 'gamelan-jawa-timur'),
  ('banten', 'Gamelan Banten', '<p><strong>Gamelan Banten</strong> adalah musik tradisional khas Banten.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Serang', 'https://www.google.com/maps/search/?api=1&query=Gamelan%20Banten%20Banten', 'gamelan-banten'),
  ('bali', 'Gamelan Gong Kebyar', '<p><strong>Gamelan Gong Kebyar</strong> adalah musik tradisional khas Bali.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Denpasar', 'https://www.google.com/maps/search/?api=1&query=Gamelan%20Gong%20Kebyar%20Bali', 'gamelan-gong-kebyar'),
  ('nusa-tenggara-barat', 'Gendang Beleq', '<p><strong>Gendang Beleq</strong> adalah musik tradisional khas Nusa Tenggara Barat.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Mataram', 'https://www.google.com/maps/search/?api=1&query=Gendang%20Beleq%20Nusa%20Tenggara%20Barat', 'gendang-beleq'),
  ('nusa-tenggara-timur', 'Sasando', '<p><strong>Sasando</strong> adalah musik tradisional khas Nusa Tenggara Timur.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Kupang', 'https://www.google.com/maps/search/?api=1&query=Sasando%20Nusa%20Tenggara%20Timur', 'sasando'),
  ('kalimantan-barat', 'Sape Dayak', '<p><strong>Sape Dayak</strong> adalah musik tradisional khas Kalimantan Barat.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Pontianak', 'https://www.google.com/maps/search/?api=1&query=Sape%20Dayak%20Kalimantan%20Barat', 'sape-dayak'),
  ('kalimantan-tengah', 'Garantung', '<p><strong>Garantung</strong> adalah musik tradisional khas Kalimantan Tengah.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Palangka Raya', 'https://www.google.com/maps/search/?api=1&query=Garantung%20Kalimantan%20Tengah', 'garantung'),
  ('kalimantan-selatan', 'Panting', '<p><strong>Panting</strong> adalah musik tradisional khas Kalimantan Selatan.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Banjarmasin', 'https://www.google.com/maps/search/?api=1&query=Panting%20Kalimantan%20Selatan', 'panting'),
  ('kalimantan-timur', 'Sampe Kutai', '<p><strong>Sampe Kutai</strong> adalah musik tradisional khas Kalimantan Timur.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Samarinda', 'https://www.google.com/maps/search/?api=1&query=Sampe%20Kutai%20Kalimantan%20Timur', 'sampe-kutai'),
  ('kalimantan-utara', 'Sampe Kaltara', '<p><strong>Sampe Kaltara</strong> adalah musik tradisional khas Kalimantan Utara.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Tanjung Selor', 'https://www.google.com/maps/search/?api=1&query=Sampe%20Kaltara%20Kalimantan%20Utara', 'sampe-kaltara'),
  ('sulawesi-utara', 'Kolintang', '<p><strong>Kolintang</strong> adalah musik tradisional khas Sulawesi Utara.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Manado', 'https://www.google.com/maps/search/?api=1&query=Kolintang%20Sulawesi%20Utara', 'kolintang'),
  ('sulawesi-tengah', 'Kakula', '<p><strong>Kakula</strong> adalah musik tradisional khas Sulawesi Tengah.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Palu', 'https://www.google.com/maps/search/?api=1&query=Kakula%20Sulawesi%20Tengah', 'kakula'),
  ('sulawesi-selatan', 'Keso-keso', '<p><strong>Keso-keso</strong> adalah musik tradisional khas Sulawesi Selatan.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Makassar', 'https://www.google.com/maps/search/?api=1&query=Keso-keso%20Sulawesi%20Selatan', 'keso-keso'),
  ('sulawesi-tenggara', 'Gambus Sultra', '<p><strong>Gambus Sultra</strong> adalah musik tradisional khas Sulawesi Tenggara.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Kendari', 'https://www.google.com/maps/search/?api=1&query=Gambus%20Sultra%20Sulawesi%20Tenggara', 'gambus-sultra'),
  ('gorontalo', 'Polopalo', '<p><strong>Polopalo</strong> adalah musik tradisional khas Gorontalo.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Gorontalo', 'https://www.google.com/maps/search/?api=1&query=Polopalo%20Gorontalo', 'polopalo'),
  ('sulawesi-barat', 'Calong', '<p><strong>Calong</strong> adalah musik tradisional khas Sulawesi Barat.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Mamuju', 'https://www.google.com/maps/search/?api=1&query=Calong%20Sulawesi%20Barat', 'calong'),
  ('maluku', 'Tifa Maluku', '<p><strong>Tifa Maluku</strong> adalah musik tradisional khas Maluku.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Ambon', 'https://www.google.com/maps/search/?api=1&query=Tifa%20Maluku%20Maluku', 'tifa-maluku'),
  ('maluku-utara', 'Tifa Malut', '<p><strong>Tifa Malut</strong> adalah musik tradisional khas Maluku Utara.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Ternate', 'https://www.google.com/maps/search/?api=1&query=Tifa%20Malut%20Maluku%20Utara', 'tifa-malut'),
  ('papua', 'Tifa Papua', '<p><strong>Tifa Papua</strong> adalah musik tradisional khas Papua.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Jayapura', 'https://www.google.com/maps/search/?api=1&query=Tifa%20Papua%20Papua', 'tifa-papua'),
  ('papua-barat', 'Tifa Papua Barat', '<p><strong>Tifa Papua Barat</strong> adalah musik tradisional khas Papua Barat.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Manokwari', 'https://www.google.com/maps/search/?api=1&query=Tifa%20Papua%20Barat%20Papua%20Barat', 'tifa-papua-barat'),
  ('papua-selatan', 'Tifa Papua Selatan', '<p><strong>Tifa Papua Selatan</strong> adalah musik tradisional khas Papua Selatan.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Merauke', 'https://www.google.com/maps/search/?api=1&query=Tifa%20Papua%20Selatan%20Papua%20Selatan', 'tifa-papua-selatan'),
  ('papua-tengah', 'Tifa Papua Tengah', '<p><strong>Tifa Papua Tengah</strong> adalah musik tradisional khas Papua Tengah.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Nabire', 'https://www.google.com/maps/search/?api=1&query=Tifa%20Papua%20Tengah%20Papua%20Tengah', 'tifa-papua-tengah'),
  ('papua-pegunungan', 'Pikon', '<p><strong>Pikon</strong> adalah musik tradisional khas Papua Pegunungan.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Wamena', 'https://www.google.com/maps/search/?api=1&query=Pikon%20Papua%20Pegunungan', 'pikon'),
  ('papua-barat-daya', 'Tifa Papua Barat Daya', '<p><strong>Tifa Papua Barat Daya</strong> adalah musik tradisional khas Papua Barat Daya.</p><p>TODO: lengkapi sejarah, alat musik, cara memainkan, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80', 'Sorong', 'https://www.google.com/maps/search/?api=1&query=Tifa%20Papua%20Barat%20Daya%20Papua%20Barat%20Daya', 'tifa-papua-barat-daya')
) AS v(province_slug, name, content, media_url, location, maps_url, slug)
JOIN provinces p ON p.slug = v.province_slug;

COMMIT;
