-- Base seed: pertunjukan (1 slot × 38 provinsi)
-- category slug: pertunjukan
-- Lengkapi content/media, lalu jalankan SQL di Supabase.

BEGIN;

DELETE FROM cultures WHERE category_id = (SELECT id FROM categories WHERE slug = 'pertunjukan');

INSERT INTO cultures (province_id, category_id, name, content, media_url, location, maps_url, slug)
SELECT p.id, c.id, v.name, v.content, v.media_url, v.location, v.maps_url, v.slug
FROM (SELECT id FROM categories WHERE slug = 'pertunjukan') c
CROSS JOIN (VALUES
  ('aceh', 'Didong', '<p><strong>Didong</strong> adalah pertunjukan khas Aceh.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Banda Aceh', 'https://www.google.com/maps/search/?api=1&query=Didong%20Aceh', 'didong'),
  ('sumatera-utara', 'Opera Batak', '<p><strong>Opera Batak</strong> adalah pertunjukan khas Sumatera Utara.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Medan', 'https://www.google.com/maps/search/?api=1&query=Opera%20Batak%20Sumatera%20Utara', 'opera-batak'),
  ('sumatera-barat', 'Randai', '<p><strong>Randai</strong> adalah pertunjukan khas Sumatera Barat.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Padang', 'https://www.google.com/maps/search/?api=1&query=Randai%20Sumatera%20Barat', 'randai'),
  ('riau', 'Mak Yong Riau', '<p><strong>Mak Yong Riau</strong> adalah pertunjukan khas Riau.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Pekanbaru', 'https://www.google.com/maps/search/?api=1&query=Mak%20Yong%20Riau%20Riau', 'mak-yong-riau'),
  ('jambi', 'Dendang Jambi', '<p><strong>Dendang Jambi</strong> adalah pertunjukan khas Jambi.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Jambi', 'https://www.google.com/maps/search/?api=1&query=Dendang%20Jambi%20Jambi', 'dendang-jambi'),
  ('sumatera-selatan', 'Dulmuluk', '<p><strong>Dulmuluk</strong> adalah pertunjukan khas Sumatera Selatan.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Palembang', 'https://www.google.com/maps/search/?api=1&query=Dulmuluk%20Sumatera%20Selatan', 'dulmuluk'),
  ('bengkulu', 'Dendang Bengkulu', '<p><strong>Dendang Bengkulu</strong> adalah pertunjukan khas Bengkulu.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Bengkulu', 'https://www.google.com/maps/search/?api=1&query=Dendang%20Bengkulu%20Bengkulu', 'dendang-bengkulu'),
  ('lampung', 'Hadrah Lampung', '<p><strong>Hadrah Lampung</strong> adalah pertunjukan khas Lampung.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Bandar Lampung', 'https://www.google.com/maps/search/?api=1&query=Hadrah%20Lampung%20Lampung', 'hadrah-lampung'),
  ('kepulauan-bangka-belitung', 'Sepen Babel', '<p><strong>Sepen Babel</strong> adalah pertunjukan khas Kepulauan Bangka Belitung.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Pangkalpinang', 'https://www.google.com/maps/search/?api=1&query=Sepen%20Babel%20Kepulauan%20Bangka%20Belitung', 'sepen-babel'),
  ('kepulauan-riau', 'Makyong Kepri', '<p><strong>Makyong Kepri</strong> adalah pertunjukan khas Kepulauan Riau.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Tanjung Pinang', 'https://www.google.com/maps/search/?api=1&query=Makyong%20Kepri%20Kepulauan%20Riau', 'makyong-kepri'),
  ('dki-jakarta', 'Lenong Betawi', '<p><strong>Lenong Betawi</strong> adalah pertunjukan khas DKI Jakarta.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Jakarta', 'https://www.google.com/maps/search/?api=1&query=Lenong%20Betawi%20DKI%20Jakarta', 'lenong-betawi'),
  ('jawa-barat', 'Wayang Golek', '<p><strong>Wayang Golek</strong> adalah pertunjukan khas Jawa Barat.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Bandung', 'https://www.google.com/maps/search/?api=1&query=Wayang%20Golek%20Jawa%20Barat', 'wayang-golek'),
  ('jawa-tengah', 'Wayang Kulit', '<p><strong>Wayang Kulit</strong> adalah pertunjukan khas Jawa Tengah.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Surakarta', 'https://www.google.com/maps/search/?api=1&query=Wayang%20Kulit%20Jawa%20Tengah', 'wayang-kulit'),
  ('di-yogyakarta', 'Wayang Wong', '<p><strong>Wayang Wong</strong> adalah pertunjukan khas DI Yogyakarta.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Yogyakarta', 'https://www.google.com/maps/search/?api=1&query=Wayang%20Wong%20DI%20Yogyakarta', 'wayang-wong'),
  ('jawa-timur', 'Ludruk', '<p><strong>Ludruk</strong> adalah pertunjukan khas Jawa Timur.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Surabaya', 'https://www.google.com/maps/search/?api=1&query=Ludruk%20Jawa%20Timur', 'ludruk'),
  ('banten', 'Debus Pertunjukan', '<p><strong>Debus Pertunjukan</strong> adalah pertunjukan khas Banten.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Serang', 'https://www.google.com/maps/search/?api=1&query=Debus%20Pertunjukan%20Banten', 'debus-pertunjukan'),
  ('bali', 'Sendratari Ramayana Bali', '<p><strong>Sendratari Ramayana Bali</strong> adalah pertunjukan khas Bali.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Denpasar', 'https://www.google.com/maps/search/?api=1&query=Sendratari%20Ramayana%20Bali%20Bali', 'sendratari-ramayana-bali'),
  ('nusa-tenggara-barat', 'Cupak Gerantang', '<p><strong>Cupak Gerantang</strong> adalah pertunjukan khas Nusa Tenggara Barat.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Mataram', 'https://www.google.com/maps/search/?api=1&query=Cupak%20Gerantang%20Nusa%20Tenggara%20Barat', 'cupak-gerantang'),
  ('nusa-tenggara-timur', 'Caci', '<p><strong>Caci</strong> adalah pertunjukan khas Nusa Tenggara Timur.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Kupang', 'https://www.google.com/maps/search/?api=1&query=Caci%20Nusa%20Tenggara%20Timur', 'caci'),
  ('kalimantan-barat', 'Sandiwara Dayak', '<p><strong>Sandiwara Dayak</strong> adalah pertunjukan khas Kalimantan Barat.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Pontianak', 'https://www.google.com/maps/search/?api=1&query=Sandiwara%20Dayak%20Kalimantan%20Barat', 'sandiwara-dayak'),
  ('kalimantan-tengah', 'Mamapas Lewu', '<p><strong>Mamapas Lewu</strong> adalah pertunjukan khas Kalimantan Tengah.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Palangka Raya', 'https://www.google.com/maps/search/?api=1&query=Mamapas%20Lewu%20Kalimantan%20Tengah', 'mamapas-lewu'),
  ('kalimantan-selatan', 'Mamanda', '<p><strong>Mamanda</strong> adalah pertunjukan khas Kalimantan Selatan.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Banjarmasin', 'https://www.google.com/maps/search/?api=1&query=Mamanda%20Kalimantan%20Selatan', 'mamanda'),
  ('kalimantan-timur', 'Teater Adat Kutai', '<p><strong>Teater Adat Kutai</strong> adalah pertunjukan khas Kalimantan Timur.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Samarinda', 'https://www.google.com/maps/search/?api=1&query=Teater%20Adat%20Kutai%20Kalimantan%20Timur', 'teater-adat-kutai'),
  ('kalimantan-utara', 'Pertunjukan Adat Kaltara', '<p><strong>Pertunjukan Adat Kaltara</strong> adalah pertunjukan khas Kalimantan Utara.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Tanjung Selor', 'https://www.google.com/maps/search/?api=1&query=Pertunjukan%20Adat%20Kaltara%20Kalimantan%20Utara', 'pertunjukan-adat-kaltara'),
  ('sulawesi-utara', 'Kabasaran', '<p><strong>Kabasaran</strong> adalah pertunjukan khas Sulawesi Utara.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Manado', 'https://www.google.com/maps/search/?api=1&query=Kabasaran%20Sulawesi%20Utara', 'kabasaran'),
  ('sulawesi-tengah', 'Pertunjukan Adat Kaili', '<p><strong>Pertunjukan Adat Kaili</strong> adalah pertunjukan khas Sulawesi Tengah.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Palu', 'https://www.google.com/maps/search/?api=1&query=Pertunjukan%20Adat%20Kaili%20Sulawesi%20Tengah', 'pertunjukan-adat-kaili'),
  ('sulawesi-selatan', 'Sinrilik', '<p><strong>Sinrilik</strong> adalah pertunjukan khas Sulawesi Selatan.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Makassar', 'https://www.google.com/maps/search/?api=1&query=Sinrilik%20Sulawesi%20Selatan', 'sinrilik'),
  ('sulawesi-tenggara', 'Lulo Pertunjukan', '<p><strong>Lulo Pertunjukan</strong> adalah pertunjukan khas Sulawesi Tenggara.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Kendari', 'https://www.google.com/maps/search/?api=1&query=Lulo%20Pertunjukan%20Sulawesi%20Tenggara', 'lulo-pertunjukan'),
  ('gorontalo', 'Pantung', '<p><strong>Pantung</strong> adalah pertunjukan khas Gorontalo.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Gorontalo', 'https://www.google.com/maps/search/?api=1&query=Pantung%20Gorontalo', 'pantung'),
  ('sulawesi-barat', 'Kalindaqdaq', '<p><strong>Kalindaqdaq</strong> adalah pertunjukan khas Sulawesi Barat.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Mamuju', 'https://www.google.com/maps/search/?api=1&query=Kalindaqdaq%20Sulawesi%20Barat', 'kalindaqdaq'),
  ('maluku', 'Pantun Tifa Maluku', '<p><strong>Pantun Tifa Maluku</strong> adalah pertunjukan khas Maluku.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Ambon', 'https://www.google.com/maps/search/?api=1&query=Pantun%20Tifa%20Maluku%20Maluku', 'pantun-tifa-maluku'),
  ('maluku-utara', 'Legu Salai Pertunjukan', '<p><strong>Legu Salai Pertunjukan</strong> adalah pertunjukan khas Maluku Utara.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Ternate', 'https://www.google.com/maps/search/?api=1&query=Legu%20Salai%20Pertunjukan%20Maluku%20Utara', 'legu-salai-pertunjukan'),
  ('papua', 'Pertunjukan Bakar Batu', '<p><strong>Pertunjukan Bakar Batu</strong> adalah pertunjukan khas Papua.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Jayapura', 'https://www.google.com/maps/search/?api=1&query=Pertunjukan%20Bakar%20Batu%20Papua', 'pertunjukan-bakar-batu'),
  ('papua-barat', 'Pertunjukan Adat Papua Barat', '<p><strong>Pertunjukan Adat Papua Barat</strong> adalah pertunjukan khas Papua Barat.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Manokwari', 'https://www.google.com/maps/search/?api=1&query=Pertunjukan%20Adat%20Papua%20Barat%20Papua%20Barat', 'pertunjukan-adat-papua-barat'),
  ('papua-selatan', 'Pertunjukan Adat Papua Selatan', '<p><strong>Pertunjukan Adat Papua Selatan</strong> adalah pertunjukan khas Papua Selatan.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Merauke', 'https://www.google.com/maps/search/?api=1&query=Pertunjukan%20Adat%20Papua%20Selatan%20Papua%20Selatan', 'pertunjukan-adat-papua-selatan'),
  ('papua-tengah', 'Pertunjukan Adat Papua Tengah', '<p><strong>Pertunjukan Adat Papua Tengah</strong> adalah pertunjukan khas Papua Tengah.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Nabire', 'https://www.google.com/maps/search/?api=1&query=Pertunjukan%20Adat%20Papua%20Tengah%20Papua%20Tengah', 'pertunjukan-adat-papua-tengah'),
  ('papua-pegunungan', 'Pertunjukan Adat Pegunungan', '<p><strong>Pertunjukan Adat Pegunungan</strong> adalah pertunjukan khas Papua Pegunungan.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Wamena', 'https://www.google.com/maps/search/?api=1&query=Pertunjukan%20Adat%20Pegunungan%20Papua%20Pegunungan', 'pertunjukan-adat-pegunungan'),
  ('papua-barat-daya', 'Pertunjukan Adat Papua Barat Daya', '<p><strong>Pertunjukan Adat Papua Barat Daya</strong> adalah pertunjukan khas Papua Barat Daya.</p><p>TODO: lengkapi sejarah, bentuk penyajian, tokoh, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80', 'Sorong', 'https://www.google.com/maps/search/?api=1&query=Pertunjukan%20Adat%20Papua%20Barat%20Daya%20Papua%20Barat%20Daya', 'pertunjukan-adat-papua-barat-daya')
) AS v(province_slug, name, content, media_url, location, maps_url, slug)
JOIN provinces p ON p.slug = v.province_slug;

COMMIT;
