-- Base seed: ritual-dan-adat (1 slot × 38 provinsi)
-- category slug: ritual-dan-adat
-- Lengkapi content/media, lalu jalankan SQL di Supabase.

BEGIN;

DELETE FROM cultures WHERE category_id = (SELECT id FROM categories WHERE slug = 'ritual-dan-adat');

INSERT INTO cultures (province_id, category_id, name, content, media_url, location, maps_url, slug)
SELECT p.id, c.id, v.name, v.content, v.media_url, v.location, v.maps_url, v.slug
FROM (SELECT id FROM categories WHERE slug = 'ritual-dan-adat') c
CROSS JOIN (VALUES
  ('aceh', 'Peusijuek', '<p><strong>Peusijuek</strong> adalah ritual dan adat khas Aceh.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Banda Aceh', 'https://www.google.com/maps/search/?api=1&query=Peusijuek%20Aceh', 'peusijuek'),
  ('sumatera-utara', 'Mangokal Holi', '<p><strong>Mangokal Holi</strong> adalah ritual dan adat khas Sumatera Utara.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Medan', 'https://www.google.com/maps/search/?api=1&query=Mangokal%20Holi%20Sumatera%20Utara', 'mangokal-holi'),
  ('sumatera-barat', 'Tabuik', '<p><strong>Tabuik</strong> adalah ritual dan adat khas Sumatera Barat.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Padang', 'https://www.google.com/maps/search/?api=1&query=Tabuik%20Sumatera%20Barat', 'tabuik'),
  ('riau', 'Belian Melayu', '<p><strong>Belian Melayu</strong> adalah ritual dan adat khas Riau.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Pekanbaru', 'https://www.google.com/maps/search/?api=1&query=Belian%20Melayu%20Riau', 'belian-melayu'),
  ('jambi', 'Besale', '<p><strong>Besale</strong> adalah ritual dan adat khas Jambi.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Jambi', 'https://www.google.com/maps/search/?api=1&query=Besale%20Jambi', 'besale'),
  ('sumatera-selatan', 'Sedekah Laut Palembang', '<p><strong>Sedekah Laut Palembang</strong> adalah ritual dan adat khas Sumatera Selatan.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Palembang', 'https://www.google.com/maps/search/?api=1&query=Sedekah%20Laut%20Palembang%20Sumatera%20Selatan', 'sedekah-laut-palembang'),
  ('bengkulu', 'Tabot', '<p><strong>Tabot</strong> adalah ritual dan adat khas Bengkulu.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Bengkulu', 'https://www.google.com/maps/search/?api=1&query=Tabot%20Bengkulu', 'tabot'),
  ('lampung', 'Begawi', '<p><strong>Begawi</strong> adalah ritual dan adat khas Lampung.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Bandar Lampung', 'https://www.google.com/maps/search/?api=1&query=Begawi%20Lampung', 'begawi'),
  ('kepulauan-bangka-belitung', 'Ruah Kampung Babel', '<p><strong>Ruah Kampung Babel</strong> adalah ritual dan adat khas Kepulauan Bangka Belitung.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Pangkalpinang', 'https://www.google.com/maps/search/?api=1&query=Ruah%20Kampung%20Babel%20Kepulauan%20Bangka%20Belitung', 'ruah-kampung-babel'),
  ('kepulauan-riau', 'Mandi Safar', '<p><strong>Mandi Safar</strong> adalah ritual dan adat khas Kepulauan Riau.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Tanjung Pinang', 'https://www.google.com/maps/search/?api=1&query=Mandi%20Safar%20Kepulauan%20Riau', 'mandi-safar'),
  ('dki-jakarta', 'Palang Pintu', '<p><strong>Palang Pintu</strong> adalah ritual dan adat khas DKI Jakarta.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Jakarta', 'https://www.google.com/maps/search/?api=1&query=Palang%20Pintu%20DKI%20Jakarta', 'palang-pintu'),
  ('jawa-barat', 'Seren Taun', '<p><strong>Seren Taun</strong> adalah ritual dan adat khas Jawa Barat.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Bandung', 'https://www.google.com/maps/search/?api=1&query=Seren%20Taun%20Jawa%20Barat', 'seren-taun'),
  ('jawa-tengah', 'Sekaten', '<p><strong>Sekaten</strong> adalah ritual dan adat khas Jawa Tengah.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Surakarta', 'https://www.google.com/maps/search/?api=1&query=Sekaten%20Jawa%20Tengah', 'sekaten'),
  ('di-yogyakarta', 'Labuhan', '<p><strong>Labuhan</strong> adalah ritual dan adat khas DI Yogyakarta.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Yogyakarta', 'https://www.google.com/maps/search/?api=1&query=Labuhan%20DI%20Yogyakarta', 'labuhan'),
  ('jawa-timur', 'Larung Sesaji', '<p><strong>Larung Sesaji</strong> adalah ritual dan adat khas Jawa Timur.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Surabaya', 'https://www.google.com/maps/search/?api=1&query=Larung%20Sesaji%20Jawa%20Timur', 'larung-sesaji'),
  ('banten', 'Debus', '<p><strong>Debus</strong> adalah ritual dan adat khas Banten.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Serang', 'https://www.google.com/maps/search/?api=1&query=Debus%20Banten', 'debus'),
  ('bali', 'Ngaben', '<p><strong>Ngaben</strong> adalah ritual dan adat khas Bali.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Denpasar', 'https://www.google.com/maps/search/?api=1&query=Ngaben%20Bali', 'ngaben'),
  ('nusa-tenggara-barat', 'Bau Nyale', '<p><strong>Bau Nyale</strong> adalah ritual dan adat khas Nusa Tenggara Barat.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Mataram', 'https://www.google.com/maps/search/?api=1&query=Bau%20Nyale%20Nusa%20Tenggara%20Barat', 'bau-nyale'),
  ('nusa-tenggara-timur', 'Pasola', '<p><strong>Pasola</strong> adalah ritual dan adat khas Nusa Tenggara Timur.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Kupang', 'https://www.google.com/maps/search/?api=1&query=Pasola%20Nusa%20Tenggara%20Timur', 'pasola'),
  ('kalimantan-barat', 'Gawai Dayak', '<p><strong>Gawai Dayak</strong> adalah ritual dan adat khas Kalimantan Barat.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Pontianak', 'https://www.google.com/maps/search/?api=1&query=Gawai%20Dayak%20Kalimantan%20Barat', 'gawai-dayak'),
  ('kalimantan-tengah', 'Tiwah', '<p><strong>Tiwah</strong> adalah ritual dan adat khas Kalimantan Tengah.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Palangka Raya', 'https://www.google.com/maps/search/?api=1&query=Tiwah%20Kalimantan%20Tengah', 'tiwah'),
  ('kalimantan-selatan', 'Baayun Maulid', '<p><strong>Baayun Maulid</strong> adalah ritual dan adat khas Kalimantan Selatan.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Banjarmasin', 'https://www.google.com/maps/search/?api=1&query=Baayun%20Maulid%20Kalimantan%20Selatan', 'baayun-maulid'),
  ('kalimantan-timur', 'Erau', '<p><strong>Erau</strong> adalah ritual dan adat khas Kalimantan Timur.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Samarinda', 'https://www.google.com/maps/search/?api=1&query=Erau%20Kalimantan%20Timur', 'erau'),
  ('kalimantan-utara', 'Gawai Kaltara', '<p><strong>Gawai Kaltara</strong> adalah ritual dan adat khas Kalimantan Utara.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Tanjung Selor', 'https://www.google.com/maps/search/?api=1&query=Gawai%20Kaltara%20Kalimantan%20Utara', 'gawai-kaltara'),
  ('sulawesi-utara', 'Foso Rumages', '<p><strong>Foso Rumages</strong> adalah ritual dan adat khas Sulawesi Utara.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Manado', 'https://www.google.com/maps/search/?api=1&query=Foso%20Rumages%20Sulawesi%20Utara', 'foso-rumages'),
  ('sulawesi-tengah', 'Nosu', '<p><strong>Nosu</strong> adalah ritual dan adat khas Sulawesi Tengah.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Palu', 'https://www.google.com/maps/search/?api=1&query=Nosu%20Sulawesi%20Tengah', 'nosu'),
  ('sulawesi-selatan', 'Rambu Solo', '<p><strong>Rambu Solo</strong> adalah ritual dan adat khas Sulawesi Selatan.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Makassar', 'https://www.google.com/maps/search/?api=1&query=Rambu%20Solo%20Sulawesi%20Selatan', 'rambu-solo'),
  ('sulawesi-tenggara', 'Mosehe', '<p><strong>Mosehe</strong> adalah ritual dan adat khas Sulawesi Tenggara.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Kendari', 'https://www.google.com/maps/search/?api=1&query=Mosehe%20Sulawesi%20Tenggara', 'mosehe'),
  ('gorontalo', 'Momuyawan', '<p><strong>Momuyawan</strong> adalah ritual dan adat khas Gorontalo.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Gorontalo', 'https://www.google.com/maps/search/?api=1&query=Momuyawan%20Gorontalo', 'momuyawan'),
  ('sulawesi-barat', 'Sayyang Pattuqduq', '<p><strong>Sayyang Pattuqduq</strong> adalah ritual dan adat khas Sulawesi Barat.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Mamuju', 'https://www.google.com/maps/search/?api=1&query=Sayyang%20Pattuqduq%20Sulawesi%20Barat', 'sayyang-pattuqduq'),
  ('maluku', 'Pela Gandong', '<p><strong>Pela Gandong</strong> adalah ritual dan adat khas Maluku.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Ambon', 'https://www.google.com/maps/search/?api=1&query=Pela%20Gandong%20Maluku', 'pela-gandong'),
  ('maluku-utara', 'Legu Gam', '<p><strong>Legu Gam</strong> adalah ritual dan adat khas Maluku Utara.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Ternate', 'https://www.google.com/maps/search/?api=1&query=Legu%20Gam%20Maluku%20Utara', 'legu-gam'),
  ('papua', 'Bakar Batu', '<p><strong>Bakar Batu</strong> adalah ritual dan adat khas Papua.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Jayapura', 'https://www.google.com/maps/search/?api=1&query=Bakar%20Batu%20Papua', 'bakar-batu'),
  ('papua-barat', 'Bakar Batu Papua Barat', '<p><strong>Bakar Batu Papua Barat</strong> adalah ritual dan adat khas Papua Barat.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Manokwari', 'https://www.google.com/maps/search/?api=1&query=Bakar%20Batu%20Papua%20Barat%20Papua%20Barat', 'bakar-batu-papua-barat'),
  ('papua-selatan', 'Bakar Batu Papua Selatan', '<p><strong>Bakar Batu Papua Selatan</strong> adalah ritual dan adat khas Papua Selatan.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Merauke', 'https://www.google.com/maps/search/?api=1&query=Bakar%20Batu%20Papua%20Selatan%20Papua%20Selatan', 'bakar-batu-papua-selatan'),
  ('papua-tengah', 'Bakar Batu Papua Tengah', '<p><strong>Bakar Batu Papua Tengah</strong> adalah ritual dan adat khas Papua Tengah.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Nabire', 'https://www.google.com/maps/search/?api=1&query=Bakar%20Batu%20Papua%20Tengah%20Papua%20Tengah', 'bakar-batu-papua-tengah'),
  ('papua-pegunungan', 'Bakar Batu Pegunungan', '<p><strong>Bakar Batu Pegunungan</strong> adalah ritual dan adat khas Papua Pegunungan.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Wamena', 'https://www.google.com/maps/search/?api=1&query=Bakar%20Batu%20Pegunungan%20Papua%20Pegunungan', 'bakar-batu-pegunungan'),
  ('papua-barat-daya', 'Bakar Batu Papua Barat Daya', '<p><strong>Bakar Batu Papua Barat Daya</strong> adalah ritual dan adat khas Papua Barat Daya.</p><p>TODO: lengkapi sejarah, rangkaian upacara, makna simbolik, dan konteks pelaksanaan.</p>', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80', 'Sorong', 'https://www.google.com/maps/search/?api=1&query=Bakar%20Batu%20Papua%20Barat%20Daya%20Papua%20Barat%20Daya', 'bakar-batu-papua-barat-daya')
) AS v(province_slug, name, content, media_url, location, maps_url, slug)
JOIN provinces p ON p.slug = v.province_slug;

COMMIT;
