-- Base seed: senjata-tradisional (1 slot × 38 provinsi)
-- category slug: senjata-tradisional
-- Lengkapi content/media, lalu jalankan SQL di Supabase.

BEGIN;

DELETE FROM cultures WHERE category_id = (SELECT id FROM categories WHERE slug = 'senjata-tradisional');

INSERT INTO cultures (province_id, category_id, name, content, media_url, location, maps_url, slug)
SELECT p.id, c.id, v.name, v.content, v.media_url, v.location, v.maps_url, v.slug
FROM (SELECT id FROM categories WHERE slug = 'senjata-tradisional') c
CROSS JOIN (VALUES
  ('aceh', 'Rencong', '<p><strong>Rencong</strong> adalah senjata tradisional khas Aceh.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Banda Aceh', 'https://www.google.com/maps/search/?api=1&query=Rencong%20Aceh', 'rencong'),
  ('sumatera-utara', 'Piso Surit', '<p><strong>Piso Surit</strong> adalah senjata tradisional khas Sumatera Utara.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Medan', 'https://www.google.com/maps/search/?api=1&query=Piso%20Surit%20Sumatera%20Utara', 'piso-surit'),
  ('sumatera-barat', 'Kerambit Minangkabau', '<p><strong>Kerambit Minangkabau</strong> adalah senjata tradisional khas Sumatera Barat.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Padang', 'https://www.google.com/maps/search/?api=1&query=Kerambit%20Minangkabau%20Sumatera%20Barat', 'kerambit-minangkabau'),
  ('riau', 'Pedang Jenawi', '<p><strong>Pedang Jenawi</strong> adalah senjata tradisional khas Riau.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Pekanbaru', 'https://www.google.com/maps/search/?api=1&query=Pedang%20Jenawi%20Riau', 'pedang-jenawi'),
  ('jambi', 'Keris Melayu Jambi', '<p><strong>Keris Melayu Jambi</strong> adalah senjata tradisional khas Jambi.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Jambi', 'https://www.google.com/maps/search/?api=1&query=Keris%20Melayu%20Jambi%20Jambi', 'keris-melayu-jambi'),
  ('sumatera-selatan', 'Keris Palembang', '<p><strong>Keris Palembang</strong> adalah senjata tradisional khas Sumatera Selatan.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Palembang', 'https://www.google.com/maps/search/?api=1&query=Keris%20Palembang%20Sumatera%20Selatan', 'keris-palembang'),
  ('bengkulu', 'Keris Bengkulu', '<p><strong>Keris Bengkulu</strong> adalah senjata tradisional khas Bengkulu.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Bengkulu', 'https://www.google.com/maps/search/?api=1&query=Keris%20Bengkulu%20Bengkulu', 'keris-bengkulu'),
  ('lampung', 'Payan', '<p><strong>Payan</strong> adalah senjata tradisional khas Lampung.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Bandar Lampung', 'https://www.google.com/maps/search/?api=1&query=Payan%20Lampung', 'payan'),
  ('kepulauan-bangka-belitung', 'Parang Bangka', '<p><strong>Parang Bangka</strong> adalah senjata tradisional khas Kepulauan Bangka Belitung.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Pangkalpinang', 'https://www.google.com/maps/search/?api=1&query=Parang%20Bangka%20Kepulauan%20Bangka%20Belitung', 'parang-bangka'),
  ('kepulauan-riau', 'Keris Melayu Kepri', '<p><strong>Keris Melayu Kepri</strong> adalah senjata tradisional khas Kepulauan Riau.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Tanjung Pinang', 'https://www.google.com/maps/search/?api=1&query=Keris%20Melayu%20Kepri%20Kepulauan%20Riau', 'keris-melayu-kepri'),
  ('dki-jakarta', 'Golok Betawi', '<p><strong>Golok Betawi</strong> adalah senjata tradisional khas DKI Jakarta.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Jakarta', 'https://www.google.com/maps/search/?api=1&query=Golok%20Betawi%20DKI%20Jakarta', 'golok-betawi'),
  ('jawa-barat', 'Kujang', '<p><strong>Kujang</strong> adalah senjata tradisional khas Jawa Barat.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Bandung', 'https://www.google.com/maps/search/?api=1&query=Kujang%20Jawa%20Barat', 'kujang'),
  ('jawa-tengah', 'Keris Jawa', '<p><strong>Keris Jawa</strong> adalah senjata tradisional khas Jawa Tengah.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Surakarta', 'https://www.google.com/maps/search/?api=1&query=Keris%20Jawa%20Jawa%20Tengah', 'keris-jawa'),
  ('di-yogyakarta', 'Keris Yogyakarta', '<p><strong>Keris Yogyakarta</strong> adalah senjata tradisional khas DI Yogyakarta.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Yogyakarta', 'https://www.google.com/maps/search/?api=1&query=Keris%20Yogyakarta%20DI%20Yogyakarta', 'keris-yogyakarta'),
  ('jawa-timur', 'Clurit', '<p><strong>Clurit</strong> adalah senjata tradisional khas Jawa Timur.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Surabaya', 'https://www.google.com/maps/search/?api=1&query=Clurit%20Jawa%20Timur', 'clurit'),
  ('banten', 'Golok Banten', '<p><strong>Golok Banten</strong> adalah senjata tradisional khas Banten.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Serang', 'https://www.google.com/maps/search/?api=1&query=Golok%20Banten%20Banten', 'golok-banten'),
  ('bali', 'Keris Bali', '<p><strong>Keris Bali</strong> adalah senjata tradisional khas Bali.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Denpasar', 'https://www.google.com/maps/search/?api=1&query=Keris%20Bali%20Bali', 'keris-bali'),
  ('nusa-tenggara-barat', 'Keris Sasak', '<p><strong>Keris Sasak</strong> adalah senjata tradisional khas Nusa Tenggara Barat.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Mataram', 'https://www.google.com/maps/search/?api=1&query=Keris%20Sasak%20Nusa%20Tenggara%20Barat', 'keris-sasak'),
  ('nusa-tenggara-timur', 'Surik', '<p><strong>Surik</strong> adalah senjata tradisional khas Nusa Tenggara Timur.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Kupang', 'https://www.google.com/maps/search/?api=1&query=Surik%20Nusa%20Tenggara%20Timur', 'surik'),
  ('kalimantan-barat', 'Mandau', '<p><strong>Mandau</strong> adalah senjata tradisional khas Kalimantan Barat.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Pontianak', 'https://www.google.com/maps/search/?api=1&query=Mandau%20Kalimantan%20Barat', 'mandau'),
  ('kalimantan-tengah', 'Mandau Dayak', '<p><strong>Mandau Dayak</strong> adalah senjata tradisional khas Kalimantan Tengah.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Palangka Raya', 'https://www.google.com/maps/search/?api=1&query=Mandau%20Dayak%20Kalimantan%20Tengah', 'mandau-dayak'),
  ('kalimantan-selatan', 'Keris Banjar', '<p><strong>Keris Banjar</strong> adalah senjata tradisional khas Kalimantan Selatan.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Banjarmasin', 'https://www.google.com/maps/search/?api=1&query=Keris%20Banjar%20Kalimantan%20Selatan', 'keris-banjar'),
  ('kalimantan-timur', 'Mandau Kutai', '<p><strong>Mandau Kutai</strong> adalah senjata tradisional khas Kalimantan Timur.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Samarinda', 'https://www.google.com/maps/search/?api=1&query=Mandau%20Kutai%20Kalimantan%20Timur', 'mandau-kutai'),
  ('kalimantan-utara', 'Mandau Kaltara', '<p><strong>Mandau Kaltara</strong> adalah senjata tradisional khas Kalimantan Utara.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Tanjung Selor', 'https://www.google.com/maps/search/?api=1&query=Mandau%20Kaltara%20Kalimantan%20Utara', 'mandau-kaltara'),
  ('sulawesi-utara', 'Parang Minahasa', '<p><strong>Parang Minahasa</strong> adalah senjata tradisional khas Sulawesi Utara.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Manado', 'https://www.google.com/maps/search/?api=1&query=Parang%20Minahasa%20Sulawesi%20Utara', 'parang-minahasa'),
  ('sulawesi-tengah', 'Parang Poso', '<p><strong>Parang Poso</strong> adalah senjata tradisional khas Sulawesi Tengah.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Palu', 'https://www.google.com/maps/search/?api=1&query=Parang%20Poso%20Sulawesi%20Tengah', 'parang-poso'),
  ('sulawesi-selatan', 'Badik', '<p><strong>Badik</strong> adalah senjata tradisional khas Sulawesi Selatan.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Makassar', 'https://www.google.com/maps/search/?api=1&query=Badik%20Sulawesi%20Selatan', 'badik'),
  ('sulawesi-tenggara', 'Pedang Tolaki', '<p><strong>Pedang Tolaki</strong> adalah senjata tradisional khas Sulawesi Tenggara.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Kendari', 'https://www.google.com/maps/search/?api=1&query=Pedang%20Tolaki%20Sulawesi%20Tenggara', 'pedang-tolaki'),
  ('gorontalo', 'Wamilo', '<p><strong>Wamilo</strong> adalah senjata tradisional khas Gorontalo.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Gorontalo', 'https://www.google.com/maps/search/?api=1&query=Wamilo%20Gorontalo', 'wamilo'),
  ('sulawesi-barat', 'Badik Mandar', '<p><strong>Badik Mandar</strong> adalah senjata tradisional khas Sulawesi Barat.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Mamuju', 'https://www.google.com/maps/search/?api=1&query=Badik%20Mandar%20Sulawesi%20Barat', 'badik-mandar'),
  ('maluku', 'Parang Salawaku', '<p><strong>Parang Salawaku</strong> adalah senjata tradisional khas Maluku.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Ambon', 'https://www.google.com/maps/search/?api=1&query=Parang%20Salawaku%20Maluku', 'parang-salawaku'),
  ('maluku-utara', 'Parang Ternate', '<p><strong>Parang Ternate</strong> adalah senjata tradisional khas Maluku Utara.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Ternate', 'https://www.google.com/maps/search/?api=1&query=Parang%20Ternate%20Maluku%20Utara', 'parang-ternate'),
  ('papua', 'Busur dan Panah Papua', '<p><strong>Busur dan Panah Papua</strong> adalah senjata tradisional khas Papua.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Jayapura', 'https://www.google.com/maps/search/?api=1&query=Busur%20dan%20Panah%20Papua%20Papua', 'busur-dan-panah-papua'),
  ('papua-barat', 'Busur Papua Barat', '<p><strong>Busur Papua Barat</strong> adalah senjata tradisional khas Papua Barat.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Manokwari', 'https://www.google.com/maps/search/?api=1&query=Busur%20Papua%20Barat%20Papua%20Barat', 'busur-papua-barat'),
  ('papua-selatan', 'Busur Papua Selatan', '<p><strong>Busur Papua Selatan</strong> adalah senjata tradisional khas Papua Selatan.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Merauke', 'https://www.google.com/maps/search/?api=1&query=Busur%20Papua%20Selatan%20Papua%20Selatan', 'busur-papua-selatan'),
  ('papua-tengah', 'Busur Papua Tengah', '<p><strong>Busur Papua Tengah</strong> adalah senjata tradisional khas Papua Tengah.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Nabire', 'https://www.google.com/maps/search/?api=1&query=Busur%20Papua%20Tengah%20Papua%20Tengah', 'busur-papua-tengah'),
  ('papua-pegunungan', 'Busur Papua Pegunungan', '<p><strong>Busur Papua Pegunungan</strong> adalah senjata tradisional khas Papua Pegunungan.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Wamena', 'https://www.google.com/maps/search/?api=1&query=Busur%20Papua%20Pegunungan%20Papua%20Pegunungan', 'busur-papua-pegunungan'),
  ('papua-barat-daya', 'Busur Papua Barat Daya', '<p><strong>Busur Papua Barat Daya</strong> adalah senjata tradisional khas Papua Barat Daya.</p><p>TODO: lengkapi sejarah, bentuk, bahan, dan fungsi budaya.</p>', 'https://images.unsplash.com/photo-1581093458791-9f3c3280e0f8?w=1200&q=80', 'Sorong', 'https://www.google.com/maps/search/?api=1&query=Busur%20Papua%20Barat%20Daya%20Papua%20Barat%20Daya', 'busur-papua-barat-daya')
) AS v(province_slug, name, content, media_url, location, maps_url, slug)
JOIN provinces p ON p.slug = v.province_slug;

COMMIT;
