-- Base seed: tari-tradisional (1 slot × 38 provinsi)
-- category slug: tari-tradisional
-- Lengkapi content/media, lalu jalankan SQL di Supabase.

BEGIN;

DELETE FROM cultures WHERE category_id = (SELECT id FROM categories WHERE slug = 'tari-tradisional');

INSERT INTO cultures (province_id, category_id, name, content, media_url, location, maps_url, slug)
SELECT p.id, c.id, v.name, v.content, v.media_url, v.location, v.maps_url, v.slug
FROM (SELECT id FROM categories WHERE slug = 'tari-tradisional') c
CROSS JOIN (VALUES
  ('aceh', 'Tari Saman', '<p><strong>Tari Saman</strong> adalah tari tradisional khas Aceh.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Banda Aceh', 'https://www.google.com/maps/search/?api=1&query=Tari%20Saman%20Aceh', 'tari-saman'),
  ('sumatera-utara', 'Tari Tortor', '<p><strong>Tari Tortor</strong> adalah tari tradisional khas Sumatera Utara.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Medan', 'https://www.google.com/maps/search/?api=1&query=Tari%20Tortor%20Sumatera%20Utara', 'tari-tortor'),
  ('sumatera-barat', 'Tari Piring', '<p><strong>Tari Piring</strong> adalah tari tradisional khas Sumatera Barat.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Padang', 'https://www.google.com/maps/search/?api=1&query=Tari%20Piring%20Sumatera%20Barat', 'tari-piring'),
  ('riau', 'Tari Zapin', '<p><strong>Tari Zapin</strong> adalah tari tradisional khas Riau.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Pekanbaru', 'https://www.google.com/maps/search/?api=1&query=Tari%20Zapin%20Riau', 'tari-zapin'),
  ('jambi', 'Tari Sekapur Sirih', '<p><strong>Tari Sekapur Sirih</strong> adalah tari tradisional khas Jambi.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Jambi', 'https://www.google.com/maps/search/?api=1&query=Tari%20Sekapur%20Sirih%20Jambi', 'tari-sekapur-sirih'),
  ('sumatera-selatan', 'Tari Gending Sriwijaya', '<p><strong>Tari Gending Sriwijaya</strong> adalah tari tradisional khas Sumatera Selatan.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Palembang', 'https://www.google.com/maps/search/?api=1&query=Tari%20Gending%20Sriwijaya%20Sumatera%20Selatan', 'tari-gending-sriwijaya'),
  ('bengkulu', 'Tari Andun', '<p><strong>Tari Andun</strong> adalah tari tradisional khas Bengkulu.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Bengkulu', 'https://www.google.com/maps/search/?api=1&query=Tari%20Andun%20Bengkulu', 'tari-andun'),
  ('lampung', 'Tari Melinting', '<p><strong>Tari Melinting</strong> adalah tari tradisional khas Lampung.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Bandar Lampung', 'https://www.google.com/maps/search/?api=1&query=Tari%20Melinting%20Lampung', 'tari-melinting'),
  ('kepulauan-bangka-belitung', 'Tari Campak', '<p><strong>Tari Campak</strong> adalah tari tradisional khas Kepulauan Bangka Belitung.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Pangkalpinang', 'https://www.google.com/maps/search/?api=1&query=Tari%20Campak%20Kepulauan%20Bangka%20Belitung', 'tari-campak'),
  ('kepulauan-riau', 'Tari Joget Dangkong', '<p><strong>Tari Joget Dangkong</strong> adalah tari tradisional khas Kepulauan Riau.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Tanjung Pinang', 'https://www.google.com/maps/search/?api=1&query=Tari%20Joget%20Dangkong%20Kepulauan%20Riau', 'tari-joget-dangkong'),
  ('dki-jakarta', 'Tari Topeng Betawi', '<p><strong>Tari Topeng Betawi</strong> adalah tari tradisional khas DKI Jakarta.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Jakarta', 'https://www.google.com/maps/search/?api=1&query=Tari%20Topeng%20Betawi%20DKI%20Jakarta', 'tari-topeng-betawi'),
  ('jawa-barat', 'Tari Jaipong', '<p><strong>Tari Jaipong</strong> adalah tari tradisional khas Jawa Barat.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Bandung', 'https://www.google.com/maps/search/?api=1&query=Tari%20Jaipong%20Jawa%20Barat', 'tari-jaipong'),
  ('jawa-tengah', 'Tari Gambyong', '<p><strong>Tari Gambyong</strong> adalah tari tradisional khas Jawa Tengah.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Surakarta', 'https://www.google.com/maps/search/?api=1&query=Tari%20Gambyong%20Jawa%20Tengah', 'tari-gambyong'),
  ('di-yogyakarta', 'Tari Bedhaya', '<p><strong>Tari Bedhaya</strong> adalah tari tradisional khas DI Yogyakarta.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Yogyakarta', 'https://www.google.com/maps/search/?api=1&query=Tari%20Bedhaya%20DI%20Yogyakarta', 'tari-bedhaya'),
  ('jawa-timur', 'Tari Remo', '<p><strong>Tari Remo</strong> adalah tari tradisional khas Jawa Timur.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Surabaya', 'https://www.google.com/maps/search/?api=1&query=Tari%20Remo%20Jawa%20Timur', 'tari-remo'),
  ('banten', 'Tari Cokek Banten', '<p><strong>Tari Cokek Banten</strong> adalah tari tradisional khas Banten.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Serang', 'https://www.google.com/maps/search/?api=1&query=Tari%20Cokek%20Banten%20Banten', 'tari-cokek-banten'),
  ('bali', 'Tari Pendet', '<p><strong>Tari Pendet</strong> adalah tari tradisional khas Bali.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Denpasar', 'https://www.google.com/maps/search/?api=1&query=Tari%20Pendet%20Bali', 'tari-pendet'),
  ('nusa-tenggara-barat', 'Tari Gendang Beleq', '<p><strong>Tari Gendang Beleq</strong> adalah tari tradisional khas Nusa Tenggara Barat.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Mataram', 'https://www.google.com/maps/search/?api=1&query=Tari%20Gendang%20Beleq%20Nusa%20Tenggara%20Barat', 'tari-gendang-beleq'),
  ('nusa-tenggara-timur', 'Tari Likurai', '<p><strong>Tari Likurai</strong> adalah tari tradisional khas Nusa Tenggara Timur.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Kupang', 'https://www.google.com/maps/search/?api=1&query=Tari%20Likurai%20Nusa%20Tenggara%20Timur', 'tari-likurai'),
  ('kalimantan-barat', 'Tari Monong', '<p><strong>Tari Monong</strong> adalah tari tradisional khas Kalimantan Barat.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Pontianak', 'https://www.google.com/maps/search/?api=1&query=Tari%20Monong%20Kalimantan%20Barat', 'tari-monong'),
  ('kalimantan-tengah', 'Tari Tambun Bungai', '<p><strong>Tari Tambun Bungai</strong> adalah tari tradisional khas Kalimantan Tengah.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Palangka Raya', 'https://www.google.com/maps/search/?api=1&query=Tari%20Tambun%20Bungai%20Kalimantan%20Tengah', 'tari-tambun-bungai'),
  ('kalimantan-selatan', 'Tari Baksa Kembang', '<p><strong>Tari Baksa Kembang</strong> adalah tari tradisional khas Kalimantan Selatan.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Banjarmasin', 'https://www.google.com/maps/search/?api=1&query=Tari%20Baksa%20Kembang%20Kalimantan%20Selatan', 'tari-baksa-kembang'),
  ('kalimantan-timur', 'Tari Datun Julud', '<p><strong>Tari Datun Julud</strong> adalah tari tradisional khas Kalimantan Timur.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Samarinda', 'https://www.google.com/maps/search/?api=1&query=Tari%20Datun%20Julud%20Kalimantan%20Timur', 'tari-datun-julud'),
  ('kalimantan-utara', 'Tari Jepen Kaltara', '<p><strong>Tari Jepen Kaltara</strong> adalah tari tradisional khas Kalimantan Utara.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Tanjung Selor', 'https://www.google.com/maps/search/?api=1&query=Tari%20Jepen%20Kaltara%20Kalimantan%20Utara', 'tari-jepen-kaltara'),
  ('sulawesi-utara', 'Tari Maengket', '<p><strong>Tari Maengket</strong> adalah tari tradisional khas Sulawesi Utara.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Manado', 'https://www.google.com/maps/search/?api=1&query=Tari%20Maengket%20Sulawesi%20Utara', 'tari-maengket'),
  ('sulawesi-tengah', 'Tari Dero', '<p><strong>Tari Dero</strong> adalah tari tradisional khas Sulawesi Tengah.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Palu', 'https://www.google.com/maps/search/?api=1&query=Tari%20Dero%20Sulawesi%20Tengah', 'tari-dero'),
  ('sulawesi-selatan', 'Tari Pakarena', '<p><strong>Tari Pakarena</strong> adalah tari tradisional khas Sulawesi Selatan.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Makassar', 'https://www.google.com/maps/search/?api=1&query=Tari%20Pakarena%20Sulawesi%20Selatan', 'tari-pakarena'),
  ('sulawesi-tenggara', 'Tari Lulo', '<p><strong>Tari Lulo</strong> adalah tari tradisional khas Sulawesi Tenggara.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Kendari', 'https://www.google.com/maps/search/?api=1&query=Tari%20Lulo%20Sulawesi%20Tenggara', 'tari-lulo'),
  ('gorontalo', 'Tari Dana-Dana', '<p><strong>Tari Dana-Dana</strong> adalah tari tradisional khas Gorontalo.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Gorontalo', 'https://www.google.com/maps/search/?api=1&query=Tari%20Dana-Dana%20Gorontalo', 'tari-dana-dana'),
  ('sulawesi-barat', 'Tari Pattudu', '<p><strong>Tari Pattudu</strong> adalah tari tradisional khas Sulawesi Barat.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Mamuju', 'https://www.google.com/maps/search/?api=1&query=Tari%20Pattudu%20Sulawesi%20Barat', 'tari-pattudu'),
  ('maluku', 'Tari Cakalele', '<p><strong>Tari Cakalele</strong> adalah tari tradisional khas Maluku.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Ambon', 'https://www.google.com/maps/search/?api=1&query=Tari%20Cakalele%20Maluku', 'tari-cakalele'),
  ('maluku-utara', 'Tari Legu Salai', '<p><strong>Tari Legu Salai</strong> adalah tari tradisional khas Maluku Utara.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Ternate', 'https://www.google.com/maps/search/?api=1&query=Tari%20Legu%20Salai%20Maluku%20Utara', 'tari-legu-salai'),
  ('papua', 'Tari Yospan', '<p><strong>Tari Yospan</strong> adalah tari tradisional khas Papua.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Jayapura', 'https://www.google.com/maps/search/?api=1&query=Tari%20Yospan%20Papua', 'tari-yospan'),
  ('papua-barat', 'Tari Suanggi', '<p><strong>Tari Suanggi</strong> adalah tari tradisional khas Papua Barat.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Manokwari', 'https://www.google.com/maps/search/?api=1&query=Tari%20Suanggi%20Papua%20Barat', 'tari-suanggi'),
  ('papua-selatan', 'Tari Yosim Papua Selatan', '<p><strong>Tari Yosim Papua Selatan</strong> adalah tari tradisional khas Papua Selatan.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Merauke', 'https://www.google.com/maps/search/?api=1&query=Tari%20Yosim%20Papua%20Selatan%20Papua%20Selatan', 'tari-yosim-papua-selatan'),
  ('papua-tengah', 'Tari Yosim Papua Tengah', '<p><strong>Tari Yosim Papua Tengah</strong> adalah tari tradisional khas Papua Tengah.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Nabire', 'https://www.google.com/maps/search/?api=1&query=Tari%20Yosim%20Papua%20Tengah%20Papua%20Tengah', 'tari-yosim-papua-tengah'),
  ('papua-pegunungan', 'Tari Perang Papua Pegunungan', '<p><strong>Tari Perang Papua Pegunungan</strong> adalah tari tradisional khas Papua Pegunungan.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Wamena', 'https://www.google.com/maps/search/?api=1&query=Tari%20Perang%20Papua%20Pegunungan%20Papua%20Pegunungan', 'tari-perang-papua-pegunungan'),
  ('papua-barat-daya', 'Tari Yosim Sorong', '<p><strong>Tari Yosim Sorong</strong> adalah tari tradisional khas Papua Barat Daya.</p><p>TODO: lengkapi sejarah, gerakan, kostum, dan konteks pertunjukan.</p>', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=80', 'Sorong', 'https://www.google.com/maps/search/?api=1&query=Tari%20Yosim%20Sorong%20Papua%20Barat%20Daya', 'tari-yosim-sorong')
) AS v(province_slug, name, content, media_url, location, maps_url, slug)
JOIN provinces p ON p.slug = v.province_slug;

COMMIT;
